[package]
name = "gengine"
version = "1.0.0"
authors = ["Chris Pro"]
description = "Tiny and picofast CSS engine"


[dependencies]
# These packages are mandatory and form the core of this package’s distribution.



